export const ADD_MARKER = 'ADD_MARKER';
export const EDIT_MARKER = 'EDIT_MARKER';


export const FETCH_GEOCODE = 'FETCH_GEOCODE';
export const FETCH_GEOCODE_SUCCESS = 'FETCH_GEOCODE_SUCCESS';
export const FETCH_GEOCODE_ERROR = 'FETCH_GEOCODE_ERROR';

export const FETCH_MARKERS = 'FETCH_MARKERS';
export const FETCH_MARKERS_SUCCESS = 'FETCH_MARKERS_SUCCESS';
export const FETCH_MARKERS_ERROR = 'FETCH_MARKERS_ERROR';

export const UPDATE_MARKER = 'UPDATE_MARKER';
export const UPDATE_MARKER_SUCCESS = 'UPDATE_MARKER_SUCCESS';
export const UPDATE_MARKER_ERROR = 'UPDATE_MARKER_ERROR';

export const DELETE_MARKER = 'DELETE_MARKER';
export const DELETE_MARKER_SUCCESS = 'DELETE_MARKER_SUCCESS';
export const DELETE_MARKER_ERROR = 'DELETE_DELETE_MARKER_ERRORGEOCODE_SUCCESS';

// TODO check how dismiss is implemented
// export const ADD_CATEGORY_DISMISS = 'ADD_CATEGORY_DISMISS';
