
export const FETCH_MARKERS = 'FETCH_MARKERS';
export const FETCH_MARKERS_SUCCESS = 'FETCH_MARKERS_SUCCESS';
export const FETCH_MARKERS_ERROR = 'FETCH_MARKERS_ERROR';

export const ADD_MARKER = 'ADD_MARKER';
export const ADD_MARKER_SUCCESS = 'ADD_SUCCESS';
export const ADD_MARKER_ERROR = 'ADD_MARKER_ERROR';

export const UPDATE_MARKER = 'UPDATE_MARKER';
export const UPDATE_MARKER_SUCCESS = 'UPDATE_MARKER_SUCCESS';
export const UPDATE_MARKER_ERROR = 'UPDATE_MARKER_ERROR';

export const DELETE_MARKER = 'DELETE_MARKER';
export const DELETE_MARKER_SUCCESS = 'DELETE_MARKER_SUCCESS';
export const DELETE_MARKER_ERROR = 'DELETE_DELETE_MARKER_ERRORGEOCODE_SUCCESS';
